### ISSUE TITLE
Typo "scale ambiguity" in section III.A

### ISSUE THREAD

**Issue by chrisoffner3d** [TongjiZhaohb/StereoCalibrator#2]
> Due to the inherent **sale** ambiguity in the uncalibrated stereo geometry

should probably read

> Due to the inherent **scale** ambiguity in the uncalibrated stereo geometry

? :)

**Comment by TongjiZhaohb** [comment]
Thank you very much for your helpful reminder. I will correct the mistake immediately！

从 Windows 版邮件发送

发件人: Chris Offner
发送时间: 2024年3月3日 21:02
收件人: TongjiZhaohb/StereoCalibrator
抄送: Subscribed
主题: [TongjiZhaohb/StereoCalibrator] Typo "scale ambiguity" in sectionIII.A (Issue #2)

Due to the inherent sale ambiguity in the uncalibrated stereo geometry
should probably read
Due to the inherent scale ambiguity in the uncalibrated stereo geometry
? :)

**Comment by chrisoffner3d** [comment]
You're very welcome, thanks for correcting it. 🙂 I'm slightly confused about the following notation:

When you write $`\boldsymbol{R}_l' = [\boldsymbol{r}_{l,1}, \boldsymbol{r}_{l,2}, \boldsymbol{r}_{l,3}]^\top`$ (and $`\boldsymbol{R}_r' = [\boldsymbol{r}_{r,1}, \boldsymbol{r}_{r,2}, \boldsymbol{r}_{r,3}]^\top`$), do you mean for $`\boldsymbol{r}_{l,i}`$ to be the $`i`$-th **column** of $`R_l`$?

Because, if so, then I don't understand the transpose here, i.e. if $`[\boldsymbol{r}_{l,1}, \boldsymbol{r}_{l,2}, \boldsymbol{r}_{l,3}]`$ means to denote three $`3 \times 1`$ column vectors stacked horizontally into a $`3 \times 3`$ rotation matrix $`R_l = \begin{bmatrix}\vert & \vert & \vert \\ \boldsymbol{r}_{l,1} & \boldsymbol{r}_{l,2} & \boldsymbol{r}_{l,3} \\ \vert & \vert & \vert\end{bmatrix}`$, then you probably don't want to transpose (and thus invert) this matrix anymore, right? Or maybe I'm missing something here?

**Comment by TongjiZhaohb** [comment]
Thank you for your inquiry. Actually, all vectors in the paper are column vectors, including those mentioned in your question. For example, $\boldsymbol{r}{l,1}, \boldsymbol{r}{l,2}, \boldsymbol{r}_{l,3}$ are three column vectors, but I want their values to form the rows of $R_l$, so I chose to transpose them. You will see similar occurrences in the subsequent equations.

从 Windows 版邮件发送

发件人: Chris Offner
发送时间: 2024年3月4日 5:17
收件人: TongjiZhaohb/StereoCalibrator
抄送: 害怕tjzhb; Comment
主题: Re: [TongjiZhaohb/StereoCalibrator] Typo "scale ambiguity" in sectionIII.A (Issue #2)

You're very welcome, thanks for correcting it. :) I'm slightly confused about the following notation:
When you write $\boldsymbol{R}_l' = [\boldsymbol{r}_{l,1}, \boldsymbol{r}_{l,2}, \boldsymbol{r}_{l,3}]^\top$ (and $\boldsymbol{R}_r' = [\boldsymbol{r}_{r,1}, \boldsymbol{r}_{r,2}, \boldsymbol{r}_{r,3}]^\top$), do you mean for $\boldsymbol{r}_{l,i}$ to be the $i$-th column of $R_l$?
Because, if so, then I don't understand the transpose here, i.e. if $[\boldsymbol{r}_{l,1}, \boldsymbol{r}_{l,2}, \boldsymbol{r}_{l,3}]$ means to denote three $3 \times 1$ column vectors stacked horizontally into a $3 \times 3$ rotation matrix, then you probably don't want to transpose (and thus invert) this matrix, so that the three vectors $\boldsymbol{r}_{l,1}, \boldsymbol{r}_{l,2},$ and $\boldsymbol{r}_{l,3}$ become the rows of $R_l$, right?

**Comment by chrisoffner** [comment]
I see, but if $`\boldsymbol{t} = -\boldsymbol{r}_{r, 1}`$, as stated in equation (7), wouldn't $`-\boldsymbol{r}_{r, 1}`$ need to be the first **column** of $`R_r`$?

Take this toy example:

```
Vector t from Camera_R to Camera_L:
	[ -0.71,  -0.71,   0.00]
	
Matrix for Camera_L:
	  0.71  -0.71   0.00  -0.35
	  0.71   0.71   0.00  -0.35
	  0.00   0.00   1.00   5.00
	  0.00   0.00   0.00   1.00
	  
Matrix for Camera_R:
	  0.71  -0.71   0.00   0.35
	  0.71   0.71   0.00   0.35
	  0.00   0.00   1.00   5.00
	  0.00   0.00   0.00   1.00
```

The vector $`-\boldsymbol{t}`$ is equal to the first column of $`R_r`$ (which is equal to $`R_l`$ in this rectified setup), not its first row.

**Comment by TongjiZhaohb** [comment]
Here is a misunderstanding in expression. In my paper, R_l and R_r represent the transformation between the coordinate systems of the left and right cameras in stereo rectification, rather than the transformation of the cameras themselves, so there is a difference of a transpose compared to the example you provided. If you derive according to the formulas (1), (5), and (6) in my paper, you can find that the formulas are consistent with each other.

从 Windows 版邮件发送

发件人: Chris Offner
发送时间: 2024年3月4日 5:45
收件人: TongjiZhaohb/StereoCalibrator
抄送: 害怕tjzhb; Comment
主题: Re: [TongjiZhaohb/StereoCalibrator] Typo "scale ambiguity" in sectionIII.A (Issue #2)

I see, but if $\boldsymbol{t} = -\boldsymbol{r}_{r, 1}$, as stated in equation (7), wouldn't $-\boldsymbol{r}_{r, 1}$ need to be the first column of $R_r$?
Take this toy example:
Vector t from Camera_R to Camera_L:
	[ -0.71,  -0.71,   0.00]
	
Matrix for Camera_L:
	  0.71  -0.71   0.00  -0.35
	  0.71   0.71   0.00  -0.35
	  0.00   0.00   1.00   5.00
	  0.00   0.00   0.00   1.00
	  
Matrix for Camera_R:
	  0.71  -0.71   0.00   0.35
	  0.71   0.71   0.00   0.35
	  0.00   0.00   1.00   5.00
	  0.00   0.00   0.00   1.00
The vector $-\boldsymbol{t}$ is equal to the first column of $R_r$ (which is equal to $R_l$ in this rectified setup), not its first row.

**Comment by chrisoffner3d** [comment]
Thank you so much for the clarification! Yes, I got confused because I was thinking in terms of a transposed definition of the rotation matrices. Thank you, both for this intriguing paper and for your helpful replies. I appreciate it! :)

**Comment by TongjiZhaohb** [comment]
Thank you for your attention to my article and the insights you've provided; it's been truly helpful! Wishing you good health and success in your research!

从 Windows 版邮件发送

发件人: Chris Offner
发送时间: 2024年3月4日 6:35
收件人: TongjiZhaohb/StereoCalibrator
抄送: 害怕tjzhb; Comment
主题: Re: [TongjiZhaohb/StereoCalibrator] Typo "scale ambiguity" in sectionIII.A (Issue #2)

Thank you so much for the clarification! Yes, I got confused because I was thinking in terms of a transposed definition of the rotation matrices. Thank you, both for this intriguing paper and for your helpful replies. I appreciate it! :)
